### ISSUE TITLE
Can't create multi cropbox in a view

### ISSUE THREAD

**Issue by sukoshi** [bupy7/jquery-cropbox#4]
i tried to create three cropbox in a view.
But it only worked for final cropbox.
Does any one have bug like that?

**Comment by bupy7** [comment]
give me code

**Comment by khoadm** [comment]
@bupy7 thank for reply me
in my view i used Cropbox like this:

```
<?=$form->field($model, 'image1')->widget(Cropbox::className(), [
        'attributeCropInfo' => 'crop_info1',
    ]); ?>
    <?=$form->field($model, 'image2')->widget(Cropbox::className(), [
        'attributeCropInfo' => 'crop_info2',
    ]); ?>
    <?=$form->field($model, 'image3')->widget(Cropbox::className(), [
        'attributeCropInfo' => 'crop_info3',
    ]); ?>
    <?=$form->field($model, 'image4')->widget(Cropbox::className(), [
        'attributeCropInfo' => 'crop_info4',
    ]); ?>
```

and only widget4 can work

**Comment by bupy7** [comment]
@khoadm this repository for JS package. You need create issue to specified repositories ([yii-cropbox](https://github.com/bupy7/yii-cropbox) or [yii2-widget-cropbox](https://github.com/bupy7/yii2-widget-cropbox)).
